apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: {{ .Values.udn.name }}
  labels:
    app: teuthology-udn
spec:
  topology: Layer2
  layer2:
    role: Secondary
    ipam:
      mode: Disabled
