---
- hosts: teuthology
  strategy: free
  pre_tasks:
    - name: Add teuthology repo
      zypper_repository:
        name: teuthology
        repo: "{{ item }}"
        auto_import_keys: yes
        disable_gpg_check: yes
        state: present
      with_items: "{{ teuthology_rpm_repo[ansible_distribution][ansible_distribution_version] }}"
      when: ansible_os_family == "Suse"
  roles:
    - ansible-managed
    - common
    - paddles
    - paddles_nodes
    - pulpito
    - teuthology
    - teuthology_workers
    - teuthology_nameserver
    - teuthology_users
    - nsupdate_web
  become: true
