import argparse
from ast import Add
from curses import meta
from email.policy import default
import sys

import teuthology.suite
from teuthology.suite import override_arg_defaults as defaults
from teuthology.config import config

desc = """
Run a suite of ceph integration tests. A suite is a directory containing
facets. A facet is a directory containing config snippets. Running a suite
means running teuthology for every configuration combination generated by
taking one config snippet from each facet. Any config files passed on the
command line will be used for every combination, and will override anything in
the suite. By specifying a subdirectory in the suite argument, it is possible
to limit the run to a specific facet. For instance -s upgrade/dumpling-x only
runs the dumpling-x facet of the upgrade suite.
"""

epilog = """
+=================+=================================================================+
| Priority        | Explanation                                                     |
+=================+=================================================================+
| N < 10          | Use this if the sky is falling and some group of tests          |
|                 | must be run ASAP.                                               |
+-----------------+-----------------------------------------------------------------+
| 10 <= N < 50    | Use this if your tests are urgent and blocking other            |
|                 | important development.                                          |
+-----------------+-----------------------------------------------------------------+
| 50 <= N < 75    | Use this if you are testing a particular feature/fix            |
|                 | and running fewer than about 25 jobs. This range is also        |
|                 | used for urgent release testing.                                |
+-----------------+-----------------------------------------------------------------+
| 75 <= N < 100   | Tech Leads regularly schedule integration tests with this       |
|                 | priority to verify pull requests against main.                  |
+-----------------+-----------------------------------------------------------------+
| 100 <= N < 150  | This priority is used for QE validation of point releases.      |
+-----------------+-----------------------------------------------------------------+
| 150 <= N < 200  | Use this priority for 100 jobs or fewer that test a particular  |
|                 | feature or fix. Results are available in about 24 hours.        |
+-----------------+-----------------------------------------------------------------+
| 200 <= N < 1000 | Use this priority for large test runs. Results are available    |
|                 | in about a week.                                                |
+-----------------+-----------------------------------------------------------------+
"""

def add_miscellaneous_args(parser_group):
    """
    Add miscellaneous arguments to the given parser.
    """
    parser_group.add_argument('-v', '--verbose', action='count', default=0,
        help='Be more verbose')
    parser_group.add_argument('--dry-run', action='store_true',
        help='Do a dry run; do not schedule anything, In combination with -vv, also call teuthology-schedule with --dry-run.')
    parser_group.add_argument('-y', '--non-interactive', action='store_true',
        help='Do not ask question and say yes when it is possible')

def add_standard_args(parser_group):
    """
    Add standard arguments to the given parser.
    """
    parser_group.add_argument('config_yaml', nargs='*', metavar='<config_yaml>',
        help='Optional extra job yaml to include')
    parser_group.add_argument('-s', '--suite',
        help='The suite to schedule')
    parser_group.add_argument('--wait', action='store_true',
        help='Block until the suite is finished')
    parser_group.add_argument('-c', '--ceph',
        default=defaults('--ceph-branch', 'main'),
        help='The ceph branch to run against [default: %(default)s]')
    parser_group.add_argument('-S', '--sha1',
        help='The ceph sha1 to run against (overrides -c). If both -S and -c are supplied, -S wins, and there is no validation that sha1 is contained in the branch')
    parser_group.add_argument('-n', '--newest', type=int,
        default=0,
        help='Search for the newest revision built on all required distro/versions, starting from either --ceph or --sha1, backtracking up to <newest> commits [default: %(default)s]')
    parser_group.add_argument('-k', '--kernel',
    default='distro',
        help='The kernel branch to run against use `none` to bypass kernel task. [default: %(default)s]')
    parser_group.add_argument('-f', '--flavor',
        default='default',
        help='The ceph packages shaman flavor to run with: (`default`, `crimson`, `notcmalloc`, `jaeger`) [default: %(default)s]')
    parser_group.add_argument('-t', '--teuthology-branch',
        help='The teuthology branch to run against.\
            Default value is determined in the next order.\
            There is TEUTH_BRANCH environment variable set.\
            There is `qa/.teuthology_branch` present in \
            the suite repo and contains non-empty string.\
            There is `teuthology_branch` present in one of \
            the user or system `teuthology.yaml` configuration \
            files respectively, otherwise use `main`.')
    parser_group.add_argument('-m', '--machine-type',
        default=config.default_machine_type,
        help='Machine type [default: %(default)s]')
    parser_group.add_argument('-d', '--distro',
        help='Distribution to run against')
    parser_group.add_argument('-D', '--distro-version',
        help='Distro version to run against')
    parser_group.add_argument('--ceph-repo',
        default=defaults('--ceph-repo', config.get_ceph_git_url()),
        help='Query this repository for Ceph branch and SHA1 values [default: %(default)s]')
    parser_group.add_argument('--suite-repo',
        default=defaults('--suite-repo', config.get_ceph_qa_suite_git_url()),
        help='Use tasks and suite definition in this repository [default: %(default)s]')
    parser_group.add_argument('--suite-relpath',
        default='qa',
        help='Look for tasks and suite definitions in this subdirectory [default: %(default)s]')
    parser_group.add_argument('--suite-branch',
        help='Use this suite branch instead of the ceph branch')
    parser_group.add_argument('--suite-sha1',
        help='The suite sha1 to use for the tests (overrides --suite-branch)')
    parser_group.add_argument('--suite-dir',
        help='Use this alternative directory as-is when assembling jobs from yaml fragments. This causes \
            <suite_branch> to be ignored for scheduling purposes, but it will still be used for test running. \
            The <suite_dir> must have `qa/suite` sub-directory')
    parser_group.add_argument('--validate-sha1',
        default='true',
        help='Validate that git SHA1s passed to -S exist [default: %(default)s]')
    parser_group.add_argument('--kdb',
        default='true',
        help='Enable/disable kdb in kernel [default: %(default)s]')
    parser_group.add_argument('--sleep-before-teardown', type=int,
        default=0,
        help="""Number of seconds to sleep before teardown. \
            Use with care, as this applies to all jobs in the \
            run. This option is used along with --limit one. \
            If the --limit ommitted then it's forced to 1. \
            If the --limit is greater than 4, then user must \
            confirm it interactively to avoid massive lock \
            of resources, however --non-interactive option \
            can be used to skip user input. [default: %(default)s]""")
    parser_group.add_argument('--arch',
        help='Override architecture defaults, for example, \
            aarch64, armv7l, x86_64. Normally this \
            argument should not be provided and the arch \
            is determined from --machine-type.')

def add_scheduler_args(parser_group):
    """
    Add arguments related to the scheduler to the given parser.
    """
    parser_group.add_argument('--owner',
        help='Job owner')
    parser_group.add_argument('-b', '--queue-backend',
        help='Scheduler queue backend name')
    parser_group.add_argument('-e', '--email',
        help='When tests finish or time out, send an email \
            here. May also be specified in ~/.teuthology.yaml as \
            results_email')
    parser_group.add_argument('--expire', metavar='<datetime>',
        help='Do not execute jobs in the run if they have not completed by this time. \
            Valid formats include ISO 8601, and relative offsets like \'90s\', \'30m\', \
            \'1h\', \'3d\', or \'1w\'')
    parser_group.add_argument('--rocketchat',
        help='Comma separated list of Rocket.Chat channels where \
            to send a message when tests finished or time out. \
            To be used with --sleep-before-teardown option.')
    parser_group.add_argument('-N', '--num', type=int, metavar='<num>',
        default=1,
        help='Number of times to run/queue the job [default: %(default)d]')
    parser_group.add_argument('-l', '--limit', type=int, metavar='<jobs',
        default=0,
        help='Queue at most this many jobs [default: %(default)d]')
    parser_group.add_argument('--subset',
        help='Instead of scheduling the entire suite, break the set of jobs \
            into <outof> pieces (each of which will contain each facet at least once) and schedule \
            piece <index>.  Scheduling 0/<outof>, 1/<outof>, 2/<outof> ... <outof>-1/<outof> \
            will schedule all jobs in the suite (many more than once). If specified, \
            this value can be found in results.log.')
    parser_group.add_argument('-p', '--priority', type=int,
        default=1000,
        help='Job priority (lower is sooner) [default: %(default)d]')
    parser_group.add_argument('--timeout',
        default=config.results_timeout,
        help='How long, in seconds, to wait for jobs to finish \
            before sending email. This does not kill jobs. [default: %(default)s]')
    parser_group.add_argument('--filter',
        help='Only run jobs whose description contains at least one of the keywords in the comma separated keyword string specified.')
    parser_group.add_argument('--filter-out', metavar='KEYWORDS',
        help='Do not run jobs whose description contains any of the keywords in the comma separated keyword string specified.')
    parser_group.add_argument('--filter-all', metavar='KEYWORDS',
        help='Only run jobs whose description contains each one of the keywords in the comma separated keyword string specified.')
    parser_group.add_argument('-F', '--filter-fragments', metavar='<bool>',
        default='false',
        help='Check yaml fragments too if job description \
            does not match the filters provided with options \
            --filter, --filter-out, and --filter-all. [default: %(default)s]')
    parser_group.add_argument('--archive-upload', metavar='RSYNC_DEST',
        help='Rsync destination to upload archives')
    parser_group.add_argument('--archive-upload-url', metavar='URL',
        help='Public facing URL where archives are uploaded')
    parser_group.add_argument('--throttle', metavar='SLEEP',
        help='When scheduling, wait SLEEP seconds between jobs \
            Useful to avoid bursts that may be too hard on \
            the underlying infrastructure or exceed OpenStack API \
            limits (server creation per minute for instance).')
    parser_group.add_argument('-r', '--rerun', metavar='<name>',
        help='Attempt to reschedule a run, selecting only those \
            jobs whose status are mentioned by --rerun-status. \
            Note that this is implemented by scheduling an \
            entirely new suite and including only jobs whose \
            descriptions match the selected ones. It does so \
            using the same logic as --filter. \
            Of all the flags that were passed when scheduling \
            the original run, the resulting one will only \
            inherit the --suite value. Any other arguments \
            must be passed again while scheduling. By default, \
           \'seed\' and \'subset\' will be taken from results.log, \
            but can be overide if passed again. \
            This is important for tests involving random facet \
            (path ends with \'$\' operator).')
    parser_group.add_argument('-R', '--rerun-statuses', metavar='<statuses>',
        default='fail,dead',
        help='A comma-separated list of statuses to be used with --rerun \
            Supported statuses are: \'dead\', \'fail\', \'pass\', \'queued\', \'running\', \'waiting\' [default: %(default)s]')
    parser_group.add_argument('--seed', type=int,
        default=-1,
        help='An random number mostly useful when used along with --rerun \
            argument to rerun the exact same jobs that can only be picked at random. \
            This number can be found in the output of teuthology-suite command or in results.log. \
            Pass -1 for a random seed [default: %(default)s]')
    parser_group.add_argument('--force-priority', action='store_true',
        help='Skip the priority check')
    parser_group.add_argument('--job-threshold', type=int, metavar='<threshold>',
        default=config.job_threshold,
        help='Do not allow to schedule the run if the number of jobs exceeds threshold. \
            Use 0 to allow any number [default: %(default)d]')
    parser_group.add_argument('--no-nested-subset', action='store_true',
        help='Do not perform nested suite subsets [default: false]')

def main(argv=sys.argv[1:]):
    parser = argparse.ArgumentParser(
        description=desc,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=epilog,
    )

    # Miscellaneous arguments
    parser_group = parser.add_argument_group('Miscellaneous arguments')
    add_miscellaneous_args(parser_group)

    # Standard arguments
    parser_group = parser.add_argument_group('Standard arguments')
    add_standard_args(parser_group)

    # Scheduler arguments
    parser_group = parser.add_argument_group('Scheduler arguments')
    add_scheduler_args(parser_group)

    args = parser.parse_args(argv)
    return teuthology.suite.main(args.__dict__)
