name: integration
on:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Test using docker compose v2
        run: ./start.sh
        working-directory: ./docs/docker-compose
